### ISSUE TITLE
About license?

### ISSUE THREAD

**Issue by gb-2312** [heberleonard2/terminal-style-portfolio-page#1]
Hello😋.

WOW, this github-page is so cool😂, I want to know what's license for this github pages? I just only want to use it on my personal homepage!

Thanks.

**Comment by heberleonard2** [comment]
Thanks! I added MIT license to the project. You can use for your personal homepage 😄

**Comment by gb-2312** [comment]
Hi heberleonard2, thank you very much to share and contribute this awesome project! this problem has been resolved!😄
